name = "UniDist"
uuid = "22f7d25a-af56-4830-9f7c-4430dd01f1ac"
version = "0.1.0"

authors = ["Resul Akay <resul.akay@taf-society.org> and contributors"]

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.10"
QuadGK = "2"
SpecialFunctions = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
